```{r}
library(tidyverse)
source("../General/rmb_functions.R")
```

```{r}
map <- readRDS("../Data/drought_map.RDS")
whole.otu <- readRDS("../Data/otu_unfiltered.RDS")
tax <- readRDS("../Data/tax.RDS")
```

```{r}
tax <- classify_organelle(tax)
```

Assess the microbial/organellar ratios
```{r}
org.tidy <- whole.otu %>% 
  tidy_otu() %>% 
  inner_join(tax) %>% 
  group_by(SampleID, Assignment) %>% 
  summarise(Total = sum(Count)) %>% 
  group_by(SampleID) %>% 
  mutate(RelAb = Total/sum(Total))

org.tidy %>% 
  inner_join(map, by = "SampleID") %>% 
  ggplot(aes(Tub, RelAb, fill = Assignment)) +
  geom_bar(stat = "identity") +
  #scale_fill_manual(name = "Classification", values = org.pal) +
  facet_grid(Compartment ~ Time, scales = "free") +
  theme_light() +
  theme(text = element_text(size = 20))

org.tidy %>% 
  filter(Assignment == "Microbial") %>% 
  inner_join(map, by = "SampleID") %>% 
  filter(Treatment2 != "WC_TRN") %>% 
  ggplot(aes(paste(Treatment, Tub), RelAb, fill = Treatment)) +
  geom_bar(stat = "identity") +
  facet_grid(Compartment ~ Time)

org.tidy %>% 
  filter(Assignment == "Microbial") %>% 
  inner_join(map, by = "SampleID") %>% 
  filter(Treatment2 != "WC_TRN") %>% 
  ggplot(aes(Treatment, RelAb, fill = Treatment)) +
  geom_boxplot() +
  facet_grid(Compartment ~ Time)
```

```{r}
org.tidy2 <- whole.otu %>% 
  tidy_otu() %>% 
  inner_join(tax) %>% 
  mutate(Assignment2 = case_when(Assignment != "Microbial" ~ "Organelle",
                                 OTU_ID == "1037355" ~ "OTU 1037355",
                                 TRUE ~ "Other OTU")) %>% 
  group_by(SampleID, Assignment2) %>% 
  summarise(Total = sum(Count)) %>% 
  group_by(SampleID) %>% 
  mutate(RelAb = Total/sum(Total))

org.tidy2 %>% 
  inner_join(map, by = "SampleID") %>% 
  filter(Time > 4 & Time < 10) %>% 
  ggplot(aes(Tub, RelAb, fill = Assignment2)) +
  geom_bar(stat = "identity") +
  #scale_fill_manual(name = "Classification", values = org.pal) +
  facet_grid(Compartment ~ Time, scales = "free") +
  theme_light() +
  theme(text = element_text(size = 20))

org.tidy2 %>% 
  inner_join(map, by = "SampleID") %>% 
  group_by(Compartment, Time, Treatment, Assignment2) %>% 
  summarise(TotalRelAb = mean(RelAb)) %>% 
  filter(Compartment == "ES") %>% 
  #filter(Time > 4 & Time < 10) %>% 
  #filter(Assignment2 != "Organelle") %>% 
  ggplot(aes(Treatment, TotalRelAb, fill = Assignment2)) +
  geom_bar(stat = "identity") +
  #scale_fill_manual(name = "Classification", values = org.pal) +
  facet_grid(Compartment ~ Time, scales = "free") +
  scale_fill_manual(values = c("gray25", "gray75", "red")) +
  theme_light() +
  theme(text = element_text(size = 20))

org.tidy2 %>% 
  inner_join(map, by = "SampleID") %>% 
  filter(Assignment2 != "Organelle") %>% 
  filter(Compartment == "ES") %>% 
  filter(Time > 3 & Time < 11) %>% 
  ggplot(aes(as.factor(Tub), RelAb, fill = Assignment2)) +
  geom_bar(stat = "identity") +
  #scale_fill_manual(name = "Classification", values = org.pal) +
  facet_grid(Compartment ~ Time + Treatment, scales = "free", space = "free") +
  scale_fill_manual(values = c("gray25", "gray75", "red")) +
  theme_light() +
  theme(text = element_text(size = 20))
```


Get the microbial OTUs
```{r}
micro.id <- tax %>% 
  filter(Assignment == "Microbial") %>% 
  .$OTU_ID

otu.micro <- whole.otu[row.names(whole.otu) %in% micro.id,]
otu.micro.tidy <- tidy_otu(otu.micro)
```

Get the persistent OTUs
```{r}
pers.tresh <- 0.05 * ncol(otu.micro) 

pers.stat <- otu.micro.tidy %>% 
  group_by(OTU_ID) %>% 
  summarise(Persistence = sum(Count > 0),
         TotalCounts = sum(Count),
         Status = ifelse(Persistence > pers.tresh, "Persistent", "NonPersistent")) 

pers.id <- pers.stat %>% 
  filter(Status == "Persistent") %>% 
  .$OTU_ID

otu.pers <- otu.micro[rownames(otu.micro) %in% pers.id,]
```

Explore the general persistence patterns
```{r}
pers.dot <- pers.stat %>% 
  ggplot(aes(TotalCounts, Persistence)) +
  geom_point(alpha = 0.3) +
  geom_hline(yintercept = pers.tresh, color = "red", size = 1, linetype = 2) +
  scale_x_log10() +
  theme_light() +
  theme(text = element_text(size = 20))

pers.hist <- pers.stat %>% 
  ggplot(aes(Persistence)) +
  geom_histogram(binwidth = 10) +
  geom_vline(xintercept = pers.tresh, color = "red", size = 1, linetype = 2) +
  coord_flip() +
  xlab("") +
  theme_light() +
  theme(text = element_text(size = 20),
        axis.text.y = element_blank())

cowplot::plot_grid(pers.dot, pers.hist, nrow = 1)
```

```{r}
pers.stat %>% 
  group_by(Persistence) %>% 
  summarise(CumSum = sum(TotalCounts)) %>% 
  arrange(Persistence) %>% 
  ungroup() %>% 
  arrange(Persistence) %>% 
  mutate(TotalCumSum = cumsum(CumSum)) %>% 
  mutate(PercentReads = TotalCumSum/max(TotalCumSum) * 100) %>% 
  ggplot(aes(Persistence, PercentReads)) +
  geom_vline(xintercept = pers.tresh, color = "red", size = 1, linetype = 2) +
  geom_point() +
  theme_bw() +
  theme(text = element_text(size = 15))
```


Get the sequencing depth and richness for each of the otu tables
```{r}
seqstats <- data.frame(SampleID = colnames(otu.pers),
                  PersistentSeqDepth = colSums(otu.pers),
                  MicroSeqDepth = colSums(otu.micro),
                  TotalSeqDepth = colSums(whole.otu),
                  PersistentRichness = colSums(otu.pers > 0),
                  MicroRichness = colSums(otu.micro > 0),
                  TotalRichness = colSums(whole.otu > 0))

seqstats.tidy <- seqstats %>% 
  gather(key = "Type", value = "SeqDepth", PersistentSeqDepth:TotalSeqDepth) %>% 
  mutate(Type = str_replace(Type, "SeqDepth", "")) %>% 
  gather(key = "Type2", value = "Richness", PersistentRichness:TotalRichness) %>% 
  mutate(Type2 = str_replace(Type2, "Richness", "")) %>% 
  filter(Type == Type2) %>% 
  select(-Type2) %>% 
  inner_join(map, by = "SampleID")

seqstats.tidy
```

Get more sequencing stats
```{r}
sets <- list(raw.data = whole.otu,
          no_plant = otu.micro,
          filtered = otu.pers)

stats <- data.frame(nOTUs = sapply(sets, function(x) nrow(x)),
                    mean_SeqDepth = sapply(sets, function(x) mean(colSums(x))),
                    sd_SeqDepth = sapply(sets, function(x) sd(colSums(x))),
                    TotReads = sapply(sets, function(x) sum(x)),
                    PercenOrig = sapply(sets, function(x) sum(x)/sum(whole.otu)),
                    PercenMicrobial = sapply(sets, function(x) sum(x)/sum(otu.micro)))

stats
```

```{r}
org.tidy %>% 
  mutate(Assignment2 = ifelse(Assignment == "Microbial", "Microbial", "Organelle")) %>% 
  inner_join(map, by = "SampleID") %>% 
  group_by(Compartment, Assignment2) %>% 
  summarise(Sum = sum(Total),
            median = median(RelAb))

org.tidy %>% 
  mutate(Assignment2 = ifelse(Assignment == "Microbial", "Microbial", "Organelle")) %>% 
  inner_join(map, by = "SampleID") %>% 
   group_by(Compartment, Assignment2) %>% 
  summarise(Sum = sum(Total),
            median = median(RelAb))
```

```{r}
colSums(whole.otu)
colSums(otu.micro)
colSums(otu.pers)

data.frame(SampleID = colnames(otu.pers),
           Whole = colSums(whole.otu),
           Micro = colSums(otu.micro),
           Pers = colSums(otu.pers)) %>% 
  inner_join(map, by = "SampleID") %>% 
  group_by(Compartment) %>% 
  summarise(Whole = sum(Whole),
            Micro = sum(Micro),
            Pers = sum(Pers)) %>% 
  ungroup() %>% 
  mutate(PercMicro = Micro/Whole,
         PercPers = Pers/Whole)
```

